server.port: 8080

spring.application.name: gateway


spring.cloud.gateway.routes:

- id: student
  uri: http://student
  predicates:
  - Path=/student/**

- id: course
  uri: http://course
  predicates:
    - Path=/course/**

- id: enrolment
  uri: http://enrolment
  predicates:
    - Path=/enrolment/**


spring.zipkin.sender.type: rabbit
spring.sleuth.sampler.probability: 1.0

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.profiles: docker


---
spring.profiles: kafka

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.zipkin.sender.type: kafka
spring.kafka.bootstrap-servers: kafka:9092

---
spring.profiles: prod
spring.rabbitmq.host: 172.17.0.1

# Only allow management endpoints over http in production for info, health and circuitbreakerevents
management.endpoints.web.exposure.include: health,info,circuitbreakerevents