api:

  student:
    common:
      version: 1.0.0
      title: Student API
      description: RESTful API student
      termsOfServiceUrl: terms of url
      license: all rights reserved yejun kim
      licenseUrl: https://github.com/rladpwns12

      contact:
        name: yejun kim
        url: https://github.com/rladpwns12
        email: rladpwns12@gmail.com

    create-student:
      description: Creates a student
      notes: |
        # Normal response
        Student information will save

        # Expected error responses
        1. If a student with the same student id as specified in the posted information already exists,
          an <b>422 - Unprocessable Entity</b> error with a "duplicate key" error message will be returned

    get-student:
      description: Returns a student information of the specified student id
      notes: |
        # Normal response
        If the requested student id is found the method will return student information

        # Expected partial and error responses
        If no student information is found, a <b>404 - Not Found</b> error will be returned

    get-students:
      description: Returns students information of the specified student ids
      notes: |
        # Normal response
        If the requested student ids is found the method will return students information

        # Expected partial and error responses
        If no student information is found, a <b>404 - Not Found</b> error will be returned

    update-student:
      description: Update a student
      notes: |
        # Normal response
        Student information will update

        # Expected error responses
        1. If a student with the same email as specified in the posted information already exists,
          an <b>422 - Unprocessable Entity</b> error with a "duplicate key" error message will be returned

    delete-student:
      description: Deletes a student
      notes: |
        # Normal response
        Entities for student information related to the specificed studentId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.
        This means that a delete request of a non existing student will return <b>200 Ok</b>.

server.port: 7001
server.error.include-message: always

spring.application.name: student

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

spring.data.mongodb:
  host: localhost
  port: 27017
  database: student-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: students
    group: studentsgroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    yejun: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
