api:

  course:
    common:
      version: 1.0.0
      title: Course API
      description: RESTful API course
      termsOfServiceUrl: terms of url
      license: all rights reserved yejun kim
      licenseUrl: https://github.com/rladpwns12

      contact:
        name: yejun kim
        url: https://github.com/rladpwns12
        email: rladpwns12@gmail.com

    create-course:
      description: Creates a course
      notes: |
        # Normal response
        course information will save

    get-course:
      description: Returns a course information of the specified course id
      notes: |
        # Normal response
        If the requested course id is found the method will return course information

        # Expected partial and error responses
        If no course information is found, a <b>404 - Not Found</b> error will be returned

    get-courses:
      description: Returns page of course information of the specified search option
      notes: |
        # Normal response
        Returns page of course information that matches the requested search options
        If no corresponding course exists, a null page will be returned.

    update-course:
      description: Update a course
      notes: |
        # Normal response
        course information will update

    delete-course:
      description: Deletes a course
      notes: |
        # Normal response
        Entities for course information related to the specificed courseId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.
        This means that a delete request of a non existing course will return <b>200 Ok</b>.


server.port: 7003
server.error.include-message: always

spring.application.name: course

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

spring.data.mongodb:
  host: localhost
  port: 27017
  database: courses-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: courses
    group: coursesgroup
  bindings:
    output-students:
      destination: students
      producer:
        required-groups: auditGroup
    output-enrolments:
      destination: enrolments
      producer:
        required-groups: auditGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    yejun: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb

spring.rabbitmq.host: rabbitmq

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring.cloud.stream.kafka.binder.brokers: kafka
