apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrolment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enrolment
  template:
    metadata:
      labels:
        app: enrolment
    spec:
      containers:
      - name: enrl
        image: allclegiwon/enrolment-service
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: SPRING_CONFIG_LOCATION
            value: file:/config-repo/application.yml,file:/config-repo/enrolment.yml
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 350Mi
        volumeMounts:
          - name: config-repo-volume
            mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-enrolment
---
apiVersion: v1
kind: Service
metadata:
  name: enrolment
spec:
  selector:
    app: enrolment
  ports:
    - port: 80
      targetPort: 80
