apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /enrolment
            pathType: Prefix
            backend:
              service:
                name: enrolment
                port:
                  number: 80
          - path: /course
            pathType: Prefix
            backend:
              service:
                name: course
                port:
                  number: 80
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: student
                port:
                  number: 80
          - path: /actuator/health
            pathType: Prefix
            backend:
              service:
                name: enrolment
                port:
                  number: 80
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: zipkin-server
                port:
                  number: 80

