apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: stud
        image: allclegiwon/student-service
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker"
          - name: SPRING_CONFIG_LOCATION
            value: file:/config-repo/application.yml,file:/config-repo/student.yml
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 350Mi
        volumeMounts:
          - name: config-repo-volume
            mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-student
---
apiVersion: v1
kind: Service
metadata:
  name: student
spec:
  selector:
    app: student
  ports:
    - port: 80
      targetPort: 80
